name: marquee_in_flutter
description: You can make marquee widget like html ✨
version: 1.0.4
homepage: https://github.com/eunjin3786/marquee

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter